### ISSUE TITLE
Лучше кидать подробный Exception

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#11]
https://github.com/skinirolan/Lib_Repo/blob/bfd34db46b0b532de7012c44782f36f581cc4fbc/services/VideoService.cs#L67

**Comment by WhaIsLuve** [comment]
А не базовый

**Comment by WhaIsLuve** [comment]
Если его нет, то напиши сам

**Comment by skinirolan** [comment]
Теперь кидаю NullReferenceException

**Comment by WhaIsLuve** [comment]
Посмотрел описание метода Remove у списка, ты можешь не кидать никакие исключения. Данный метод возвращает true, когда значение удалено и false, когда его нет. Соответственно ты можешь просто кидать false, а в контроллере обработать. Если true, то возвращаешь Ok, а если false, то NotFound

**Comment by skinirolan** [comment]
я подумал и решил оставить. По смысловой, что называется, нагрузке, как по мне, разницы особо нет. Если в будущем как-то помешает - поменяю
