### ISSUE TITLE
Стоит добавить обработку ошибок в данный запрос

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#13]
https://github.com/skinirolan/Lib_Repo/blob/bfd34db46b0b532de7012c44782f36f581cc4fbc/Controllers/VideoController.cs#L41

**Comment by WhaIsLuve** [comment]
как у тебя сделано в запросах удаления и обновления

**Comment by skinirolan** [comment]
Добавил
