### ISSUE TITLE
Так же можно добавить PATCH запрос

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#14]
https://github.com/skinirolan/Lib_Repo/blob/bfd34db46b0b532de7012c44782f36f581cc4fbc/Controllers/VideoController.cs#L91

**Comment by WhaIsLuve** [comment]
по моей памяти разница в PUT и PATCH в том, что в PUT ты изменяешь все параметры всегда, а PATCH можешь только какой-то определенно, а остальные останутся прежними

**Comment by skinirolan** [comment]
добавил 
Надеюсь правильно
