### ISSUE TITLE
Добавить описание методов в Swagger

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#15]
Не помню как, но можно добавить в swagger функционал, чтобы описание методов с контроллера было и в само swagger

**Comment by WhaIsLuve** [comment]
Советую подключить, так как ты пишешь открытую API и чтобы было удобно пользователям этого API разобраться с запросами

**Comment by skinirolan** [comment]
по понятным причинам не добавил)))
