### ISSUE TITLE
Описание методов можно убрать в интерфейс, а в классе поставить вместо описания тег <inheritdoc />

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#21]
https://github.com/skinirolan/Lib_Repo/blob/e8710ef8817a187ca50b969434cce8e9cca9d0df/services/VideoService.cs#L31

**Comment by WhaIsLuve** [comment]
Так у тебя будет описание методов и в интерфейсе и в классе

**Comment by skinirolan** [comment]
перенес
