### ISSUE TITLE
Можно кидать вместо методов контроллера TypedResult

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#22]
https://github.com/skinirolan/Lib_Repo/blob/be934736d6ecb049bf299fe9f56e0ad405aa257b/Controllers/VideoController.cs#L104

https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.typedresults?view=aspnetcore-8.0

**Comment by skinirolan** [comment]
буду знатб

**Comment by WhaIsLuve** [comment]
Надо не только знать, но исправить, потому что возвращать StatusCode(500) выглядит не красиво

**Comment by WhaIsLuve** [comment]
И надо вспоминать в таких случаях что это значит

**Comment by WhaIsLuve** [comment]
![image](https://github.com/user-attachments/assets/e546f2b8-b74d-48eb-851b-30dceae01c77)
вот так примерно должно выглядеть

**Comment by WhaIsLuve** [comment]
ex.Message лучше не указывать в возвращаемом типе, так как оно будет огромным и непонятным

**Comment by skinirolan** [comment]
Переделал по примеру
