### ISSUE TITLE
убрать бесполезное поле

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#24]
https://github.com/skinirolan/Lib_Repo/blob/be934736d6ecb049bf299fe9f56e0ad405aa257b/services/VideoService.cs#L11

**Comment by skinirolan** [comment]
оно используется, но его название не отражало сути, поэтому переименовал. Задавать id просто с помощью условоного count() у листа может привести к некорректной работе. Когда буду добавлять бд, тогда и уберу (скорее всего)

**Comment by WhaIsLuve** [comment]
окей, пусть будет так пока

**Comment by WhaIsLuve** [comment]
Кстати, вместо int можешь использовать GUID и тогда не надо будет иметь дополнительное поле

**Comment by skinirolan** [comment]
Наконец таки убрал это поле))
guid сделал.
