### ISSUE TITLE
Добавить логгирование ошибок

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#25]
Вот так это должно примерно выглядеть
![image](https://github.com/user-attachments/assets/f4780a64-f8ff-4a0e-93d4-ed67218e0110)
и вот так будет выглядеть в консоли
![image](https://github.com/user-attachments/assets/b5a3fbf6-7975-44cf-993c-a397b1bca18e)

Лучше, конечно, добавить специальную либу для логгирования, но пока не стоит заморачиваться и оставим так

**Comment by WhaIsLuve** [comment]
Вот так выглядит инициализация логгера 
![image](https://github.com/user-attachments/assets/6b508a7a-9b0a-49a3-a3e1-912df38cfada)

**Comment by skinirolan** [comment]
добавил
