### ISSUE TITLE
Исправить

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#26]
https://github.com/skinirolan/Lib_Repo/blob/a02dab06081f2aeecdce7bf00a798477c7ff03b5/Controllers/VideoController.cs#L73

**Comment by skinirolan** [comment]
Исправил

**Comment by WhaIsLuve** [comment]
Почему он вообще так называется? Чем AddVideo не устраивает?

**Comment by WhaIsLuve** [comment]
Так же очепятка в имени переменной
