### ISSUE TITLE
Использовать record вместо класса

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#30]
https://github.com/skinirolan/Lib_Repo/blob/40d01711a64cd81598e3f5be9985164ee4202a4b/models/VideoInput.cs#L3

**Comment by WhaIsLuve** [comment]
https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/builtin-types/record

**Comment by skinirolan** [comment]
сделал

**Comment by WhaIsLuve** [comment]
используй позиционный стиль создания рекордов

**Comment by skinirolan** [comment]
поменял
