### ISSUE TITLE
Лучше подойдет не int, а TimeSpan

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#31]
https://github.com/skinirolan/Lib_Repo/blob/40d01711a64cd81598e3f5be9985164ee4202a4b/models/Video.cs#L52

**Comment by skinirolan** [comment]
поменял

**Comment by WhaIsLuve** [comment]
https://github.com/skinirolan/Lib_Repo/blob/64a85aafd7e48e7542c8da17f08d1abd7b822f1b/models/Video.cs#L11

тут тоже надо поменять

**Comment by WhaIsLuve** [comment]
и в input классе тоже

**Comment by skinirolan** [comment]
доделано
