### ISSUE TITLE
Что???

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#36]
https://github.com/skinirolan/Lib_Repo/blob/64a85aafd7e48e7542c8da17f08d1abd7b822f1b/models/Video.cs#L35

Зачем хранить видео в миллисекундах

**Comment by WhaIsLuve** [comment]
тем более это неправда, так как ты парсишь в конструкторе из числа в секунды

**Comment by WhaIsLuve** [comment]
Исправить описание

**Comment by skinirolan** [comment]
То старое описание было

**Comment by skinirolan** [comment]
исправил
