### ISSUE TITLE
плохой роутинг

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#7]
https://github.com/skinirolan/Lib_Repo/blob/bfd34db46b0b532de7012c44782f36f581cc4fbc/Controllers/VideoController.cs#L79

лучше придумать что-нибудь другое. и вообще, насколько это необходимо? если захочется полностью почистить видео, то проще будет очистить БД, потому что в БД может быть миллион элементов или больше

**Comment by skinirolan** [comment]
Поменял

**Comment by WhaIsLuve** [comment]
решил все же оставить данный запрос, окей
