### ISSUE TITLE
Соблюдать CodeConventions

### ISSUE THREAD

**Issue by WhaIsLuve** [skinirolan/Lib_Repo#9]
https://learn.microsoft.com/ru-ru/dotnet/csharp/fundamentals/coding-style/identifier-names

Если кратко, то:
- публичные поля пишутся в стиле camelCase(`userName`)
- приватные поля пишутся в стиле camelCase с приставкой `_`(`_userName`)
- все методы должны писаться в стиле PascalCase(`GetVideo`)
- все свойства должны писаться в стиле PascalCase(`Video`)
- между знаками операций должны быть пробелы

**Comment by skinirolan** [comment]
Где увидел - исправил

**Comment by WhaIsLuve** [comment]
в контроллере неверно сделано. Публичные методы пишутся в стиле PascalCase

**Comment by WhaIsLuve** [comment]
https://github.com/skinirolan/Lib_Repo/blob/e8710ef8817a187ca50b969434cce8e9cca9d0df/services/IVideoService.cs#L8

в интерфейсе неверно, соответственно и в классе, который реализует данный интерфейс

**Comment by skinirolan** [comment]
поменял
